name: ${PROJECT_NAME}

services:
  database:
    container_name: database
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  service:
    container_name: ${PROJECT_NAME}
    depends_on:
      - database
    image: ${PROJECT_NAME}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - /app/node_modules
    env_file: ../.env
    environment:
      NODE_ENV: development
      # HTTP Server port
      PORT: 3000
      # The DB Connection string follow the format:
      # <dialect>://<username>:<password>@<hostname>/<databasepath>
      # Actually the user and password are defined in the database entrypoint
      DB_CONNECTION_STRING: postgresql://postgres:password@database/example
    ports:
      # HTTP Server port
      - 3000:3000
      # Debugger port
      - 9229:9229
    expose:
      - 3000
      - 9229
    command: pnpm dev

volumes:
  pgdata:
