name: ${PROJECT_NAME}

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlog:/var/log/rabbitmq

  database:
    container_name: database
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  service:
    depends_on:
      - database
      - rabbitmq
    extends:
      file: docker-compose.yml
      service: service
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - /app/node_modules
    env_file: ../.env
    environment:
      NODE_ENV: development
      # The DB Connection string follow the format:
      # <dialect>://<username>:<password>@<hostname>/<databasepath>
      # Actually the user and password are defined in the database entrypoint
      DB_CONNECTION_STRING: postgresql://postgres:password@database/example
      RABBITMQ_URL: amqp://admin:password@rabbitmq:5672
    ports:
      # Debugger port
      - 9229:9229
    expose:
      - 9229
    command: pnpm dev

volumes:
  pgdata: